name: ssg
github: damhiya/damhiya.github.io
author: damhiya
maintainer: damhiya@gmail.com
copyright: (c) 2022 SoonWon Moon

executables:
  ssg:
    main: Main.hs
    dependencies:
      - base
      - text
      - dhall
      - ema == 0.6.0.0
      - lvar
      - fsnotify
      - some
      - bytestring
      - shakespeare
      - blaze-html
      - pandoc
      - data-default
    default-extensions:
      - OverloadedStrings
      - LambdaCase
      - FlexibleContexts
      - FlexibleInstances
    ghc-options: -Wall -Wno-unused-matches
